name: Generate Android APK
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ”–
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js ðŸ”¨
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Install stuff ðŸ”¨
        run: npm i
        
      - name: Build app ðŸ”¨
        run: npm run build
        
      - name: Run sync command ðŸ”¨
        run: npx cap sync

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug  
        
      - name: Generate Android APK ðŸ”¨
        run: npx cap build android

      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
